using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Threading.Tasks;

namespace Mirabeau.Sql.Library.Automapping
{
    public abstract class SqlHelperWithModelMapping : DatabaseHelperBase, ISqlHelperWithModelMapping
    {
        protected ModelMapper ModelMapper { get; private set; }

        public SqlHelperWithModelMapping()
            : this(new ModelMapper())
        {

        }

        internal SqlHelperWithModelMapping(ModelMapper modelMapper)
        {
            ModelMapper = modelMapper;
        }

        #region ExecuteReaderToModel

        /// <summary>
        /// Execute a SqlCommand (that returns a resultset and takes no parameters) against the database specified in 
        /// the connection string. 
        /// </summary>
        /// <remarks>
        /// e.g.:  
        ///  IEnumerable&lt;MyModel&gt; results = ExecuteReaderToModel&lt;MyModel&gt;(connString, CommandType.StoredProcedure, "GetOrders");
        /// </remarks>
        /// <param name="connectionString">A valid connection string for a DbConnection</param>
        /// <param name="commandType">The CommandType (stored procedure, text, etc.)</param>
        /// <param name="commandText">The stored procedure name or T-SQL command</param>
        /// <returns>A DbDataReader containing the resultset generated by the command</returns>
        public IEnumerable<TModel> ExecuteReaderToModel<TModel>(string connectionString, CommandType commandType, string commandText)
        {
            using (var reader = ExecuteReader(connectionString, commandType, commandText))
            {
                return ModelMapper.MapAsync<TModel>(reader).TaskResult();
            }
        }

        /// <summary>
        /// Execute a SqlCommand (that returns a resultset and takes no parameters) against the database specified in 
        /// the connection string. 
        /// </summary>
        /// <remarks>
        /// e.g.:  
        ///  Task&lt;DbDataReader&gt; result = ExecuteReaderAsync(connString, CommandType.StoredProcedure, "GetOrders");
        /// </remarks>
        /// <param name="connectionString">A valid connection string for a DbConnection</param>
        /// <param name="commandType">The CommandType (stored procedure, text, etc.)</param>
        /// <param name="commandText">The stored procedure name or T-SQL command</param>
        /// <returns>A DbDataReader containing the resultset generated by the command</returns>
        public async Task<IEnumerable<TModel>> ExecuteReaderToModelAsync<TModel>(string connectionString, CommandType commandType, string commandText)
        {
            using (var reader = await ExecuteReaderAsync(connectionString, commandType, commandText))
            {
                return await ModelMapper.MapAsync<TModel>(reader);
            }
        }

        /// <summary>
        /// Execute a SqlCommand (that returns a resultset) against the database specified in the connection string 
        /// using the provided parameters.
        /// </summary>
        /// <remarks>
        /// e.g.:  
        ///  DbDataReader dr = ExecuteReader(connString, CommandType.StoredProcedure, "GetOrders", new DbParameter("@productId", 24));
        /// </remarks>
        /// <param name="connectionString">A valid connection string for a DbConnection</param>
        /// <param name="commandType">The CommandType (stored procedure, text, etc.)</param>
        /// <param name="commandText">The stored procedure name or T-SQL command</param>
        /// <param name="commandParameters">An array of DbParameters used to execute the command</param>
        /// <returns>A DbDataReader containing the resultset generated by the command</returns>
        public IEnumerable<TModel> ExecuteReaderToModel<TModel>(string connectionString, CommandType commandType, string commandText, params DbParameter[] commandParameters)
        {
            using (var reader = ExecuteReader(connectionString, commandType, commandText, commandParameters))
            {
                return ModelMapper.MapAsync<TModel>(reader).TaskResult();
            }
        }

        /// <summary>
        /// Execute a SqlCommand (that returns a resultset) against the database specified in the connection string 
        /// using the provided parameters.
        /// </summary>
        /// <remarks>
        /// e.g.:  
        ///  Task&lt;DbDataReader&gt; result = ExecuteReaderAsync(connString, CommandType.StoredProcedure, "GetOrders", new DbParameter("@productId", 24));
        /// </remarks>
        /// <param name="connectionString">A valid connection string for a DbConnection</param>
        /// <param name="commandType">The CommandType (stored procedure, text, etc.)</param>
        /// <param name="commandText">The stored procedure name or T-SQL command</param>
        /// <param name="commandParameters">An array of DbParameters used to execute the command</param>
        /// <returns>A DbDataReader containing the resultset generated by the command</returns>
        public async Task<IEnumerable<TModel>> ExecuteReaderToModelAsync<TModel>(string connectionString, CommandType commandType, string commandText, params DbParameter[] commandParameters)
        {
            using (var reader = await ExecuteReaderAsync(connectionString, commandType, commandText, commandParameters))
            {
                return await ModelMapper.MapAsync<TModel>(reader);
            }
        }

        /// <summary>
        /// Execute a SqlCommand (that returns a resultset) against the database specified in the connection string 
        /// using the provided parameters.
        /// </summary>
        /// <remarks>
        /// e.g.:  
        ///  DbDataReader dr = ExecuteReader(connString, CommandType.StoredProcedure, "GetOrders", new DbParameter("@productId", 24));
        /// </remarks>
        /// <param name="connectionString">A valid connection string for a DbConnection</param>
        /// <param name="commandType">The CommandType (stored procedure, text, etc.)</param>
        /// <param name="commandText">The stored procedure name or T-SQL command</param>
        /// <param name="commandParameters">An array of DbParameters used to execute the command</param>
        /// <returns>A DbDataReader containing the resultset generated by the command</returns>
        public IEnumerable<TModel> ExecuteReaderToModel<TModel>(string connectionString, CommandType commandType, string commandText, IEnumerable<DbParameter> commandParameters)
        {
            using (var reader = ExecuteReader(connectionString, commandType, commandText, commandParameters))
            {
                return ModelMapper.MapAsync<TModel>(reader).TaskResult();
            }
        }

        /// <summary>
        /// Execute a SqlCommand (that returns a resultset) against the database specified in the connection string 
        /// using the provided parameters.
        /// </summary>
        /// <remarks>
        /// e.g.:  
        ///  Task&lt;DbDataReader&gt; result = ExecuteReaderAsync(connString, CommandType.StoredProcedure, "GetOrders", new DbParameter("@productId", 24));
        /// </remarks>
        /// <param name="connectionString">A valid connection string for a DbConnection</param>
        /// <param name="commandType">The CommandType (stored procedure, text, etc.)</param>
        /// <param name="commandText">The stored procedure name or T-SQL command</param>
        /// <param name="commandParameters">An array of DbParameters used to execute the command</param>
        /// <returns>A DbDataReader containing the resultset generated by the command</returns>
        public async Task<IEnumerable<TModel>> ExecuteReaderToModelAsync<TModel>(string connectionString, CommandType commandType, string commandText, IEnumerable<DbParameter> commandParameters)
        {
            using (var reader = await ExecuteReaderAsync(connectionString, commandType, commandText, commandParameters))
            {
                return await ModelMapper.MapAsync<TModel>(reader);
            }
        }

        /// <summary>
        /// Execute a SqlCommand (that returns a resultset and takes no parameters) against the provided DbConnection. 
        /// </summary>
        /// <remarks>
        /// e.g.:  
        ///  DbDataReader dr = ExecuteReader(conn, CommandType.StoredProcedure, "GetOrders");
        /// </remarks>
        /// <param name="connection">A valid DbConnection</param>
        /// <param name="commandType">The CommandType (stored procedure, text, etc.)</param>
        /// <param name="commandText">The stored procedure name or T-SQL command</param>
        /// <returns>A DbDataReader containing the resultset generated by the command</returns>
        public IEnumerable<TModel> ExecuteReaderToModel<TModel>(DbConnection connection, CommandType commandType, string commandText)
        {
            using (var reader = ExecuteReader(connection, commandType, commandText))
            {
                return ModelMapper.MapAsync<TModel>(reader).TaskResult();
            }
        }

        /// <summary>
        /// Execute a SqlCommand (that returns a resultset and takes no parameters) against the provided DbConnection. 
        /// </summary>
        /// <remarks>
        /// e.g.:  
        ///  Task&lt;DbDataReader&gt; result = ExecuteReaderAsync(conn, CommandType.StoredProcedure, "GetOrders");
        /// </remarks>
        /// <param name="connection">A valid DbConnection</param>
        /// <param name="commandType">The CommandType (stored procedure, text, etc.)</param>
        /// <param name="commandText">The stored procedure name or T-SQL command</param>
        /// <returns>A DbDataReader containing the resultset generated by the command</returns>
        public async Task<IEnumerable<TModel>> ExecuteReaderToModelAsync<TModel>(DbConnection connection, CommandType commandType, string commandText)
        {
            using (var reader = await ExecuteReaderAsync(connection, commandType, commandText))
            {
                return await ModelMapper.MapAsync<TModel>(reader);
            }
        }

        /// <summary>
        /// Execute a SqlCommand (that returns a resultset) against the specified DbConnection 
        /// using the provided parameters.
        /// </summary>
        /// <remarks>
        /// e.g.:  
        ///  DbDataReader dr = ExecuteReader(conn, CommandType.StoredProcedure, "GetOrders", new DbParameter("@productId", 24));
        /// </remarks>
        /// <param name="connection">A valid DbConnection</param>
        /// <param name="commandType">The CommandType (stored procedure, text, etc.)</param>
        /// <param name="commandText">The stored procedure name or T-SQL command</param>
        /// <param name="commandParameters">An array of DbParameters used to execute the command</param>
        /// <returns>A DbDataReader containing the resultset generated by the command</returns>
        public IEnumerable<TModel> ExecuteReaderToModel<TModel>(DbConnection connection, CommandType commandType, string commandText, params DbParameter[] commandParameters)
        {
            using (var reader = ExecuteReader(connection, commandType, commandText, commandParameters))
            {
                return ModelMapper.MapAsync<TModel>(reader).TaskResult();
            }
        }

        /// <summary>
        /// Execute a SqlCommand (that returns a resultset) against the specified DbConnection 
        /// using the provided parameters.
        /// </summary>
        /// <remarks>
        /// e.g.:  
        ///  Task&lt;DbDataReader&gt; result = ExecuteReaderAsync(conn, CommandType.StoredProcedure, "GetOrders", new DbParameter("@productId", 24));
        /// </remarks>
        /// <param name="connection">A valid DbConnection</param>
        /// <param name="commandType">The CommandType (stored procedure, text, etc.)</param>
        /// <param name="commandText">The stored procedure name or T-SQL command</param>
        /// <param name="commandParameters">An array of DbParameters used to execute the command</param>
        /// <returns>A DbDataReader containing the resultset generated by the command</returns>
        public async Task<IEnumerable<TModel>> ExecuteReaderToModelAsync<TModel>(DbConnection connection, CommandType commandType, string commandText, params DbParameter[] commandParameters)
        {
            using (var reader = await ExecuteReaderAsync(connection, commandType, commandText, commandParameters))
            {
                return await ModelMapper.MapAsync<TModel>(reader);
            }
        }

        /// <summary>
        /// Execute a SqlCommand (that returns a resultset) against the specified DbConnection 
        /// using the provided parameters.
        /// </summary>
        /// <remarks>
        /// e.g.:  
        ///  DbDataReader dr = ExecuteReader(conn, CommandType.StoredProcedure, "GetOrders", new DbParameter("@productId", 24));
        /// </remarks>
        /// <param name="connection">A valid DbConnection</param>
        /// <param name="commandType">The CommandType (stored procedure, text, etc.)</param>
        /// <param name="commandText">The stored procedure name or T-SQL command</param>
        /// <param name="commandParameters">An array of DbParameters used to execute the command</param>
        /// <returns>A DbDataReader containing the resultset generated by the command</returns>
        public IEnumerable<TModel> ExecuteReaderToModel<TModel>(DbConnection connection, CommandType commandType, string commandText, IEnumerable<DbParameter> commandParameters)
        {
            using (var reader = ExecuteReader(connection, commandType, commandText, commandParameters))
            {
                return ModelMapper.MapAsync<TModel>(reader).TaskResult();
            }
        }

        /// <summary>
        /// Execute a SqlCommand (that returns a resultset) against the specified DbConnection 
        /// using the provided parameters.
        /// </summary>
        /// <remarks>
        /// e.g.:  
        ///  Task&lt;DbDataReader&gt; result = ExecuteReaderAsync(conn, CommandType.StoredProcedure, "GetOrders", new DbParameter("@productId", 24));
        /// </remarks>
        /// <param name="connection">A valid DbConnection</param>
        /// <param name="commandType">The CommandType (stored procedure, text, etc.)</param>
        /// <param name="commandText">The stored procedure name or T-SQL command</param>
        /// <param name="commandParameters">An array of DbParameters used to execute the command</param>
        /// <returns>A DbDataReader containing the resultset generated by the command</returns>
        public async Task<IEnumerable<TModel>> ExecuteReaderToModelAsync<TModel>(DbConnection connection, CommandType commandType, string commandText, IEnumerable<DbParameter> commandParameters)
        {
            using (DbDataReader reader = await ExecuteReaderAsync(connection, commandType, commandText, commandParameters))
            {
                return await ModelMapper.MapAsync<TModel>(reader);
            }
        }

        /// <summary>
        /// Execute a SqlCommand (that returns a resultset and takes no parameters) against the provided DbTransaction. 
        /// </summary>
        /// <remarks>
        /// e.g.:  
        ///  DbDataReader dr = ExecuteReader(trans, CommandType.StoredProcedure, "GetOrders");
        /// </remarks>
        /// <param name="transaction">A valid DbTransaction</param>
        /// <param name="commandType">The CommandType (stored procedure, text, etc.)</param>
        /// <param name="commandText">The stored procedure name or T-SQL command</param>
        /// <returns>A DbDataReader containing the resultset generated by the command</returns>
        public IEnumerable<TModel> ExecuteReaderToModel<TModel>(DbTransaction transaction, CommandType commandType, string commandText)
        {
            using (var reader = ExecuteReader(transaction, commandType, commandText))
            {
                return ModelMapper.MapAsync<TModel>(reader).TaskResult();
            }
        }

        /// <summary>
        /// Execute a SqlCommand (that returns a resultset and takes no parameters) against the provided DbTransaction. 
        /// </summary>
        /// <remarks>
        /// e.g.:  
        ///  Task&lt;DbDataReader&gt; result = ExecuteReaderAsync(trans, CommandType.StoredProcedure, "GetOrders");
        /// </remarks>
        /// <param name="transaction">A valid DbTransaction</param>
        /// <param name="commandType">The CommandType (stored procedure, text, etc.)</param>
        /// <param name="commandText">The stored procedure name or T-SQL command</param>
        /// <returns>A DbDataReader containing the resultset generated by the command</returns>
        public async Task<IEnumerable<TModel>> ExecuteReaderToModelAsync<TModel>(DbTransaction transaction, CommandType commandType, string commandText)
        {
            using (DbDataReader reader = await ExecuteReaderAsync(transaction, commandType, commandText))
            {
                return await ModelMapper.MapAsync<TModel>(reader);
            }
        }

        /// <summary>
        /// Execute a SqlCommand (that returns a resultset) against the specified DbTransaction
        /// using the provided parameters.
        /// </summary>
        /// <remarks>
        /// e.g.:  
        ///   DbDataReader dr = ExecuteReader(trans, CommandType.StoredProcedure, "GetOrders", new DbParameter("@productId", 24));
        /// </remarks>
        /// <param name="transaction">A valid DbTransaction</param>
        /// <param name="commandType">The CommandType (stored procedure, text, etc.)</param>
        /// <param name="commandText">The stored procedure name or T-SQL command</param>
        /// <param name="commandParameters">An array of DbParameters used to execute the command</param>
        /// <returns>A DbDataReader containing the resultset generated by the command</returns>
        public IEnumerable<TModel> ExecuteReaderToModel<TModel>(DbTransaction transaction, CommandType commandType, string commandText, params DbParameter[] commandParameters)
        {
            using (var reader = ExecuteReader(transaction, commandType, commandText, commandParameters))
            {
                return ModelMapper.MapAsync<TModel>(reader).TaskResult();
            }
        }

        /// <summary>
        /// Execute a SqlCommand (that returns a resultset) against the specified DbTransaction
        /// using the provided parameters.
        /// </summary>
        /// <remarks>
        /// e.g.:  
        ///   Task&lt;DbDataReader&gt; result = ExecuteReaderAsync(trans, CommandType.StoredProcedure, "GetOrders", new DbParameter("@productId", 24));
        /// </remarks>
        /// <param name="transaction">A valid DbTransaction</param>
        /// <param name="commandType">The CommandType (stored procedure, text, etc.)</param>
        /// <param name="commandText">The stored procedure name or T-SQL command</param>
        /// <param name="commandParameters">An array of DbParameters used to execute the command</param>
        /// <returns>A DbDataReader containing the resultset generated by the command</returns>
        public async Task<IEnumerable<TModel>> ExecuteReaderToModelAsync<TModel>(DbTransaction transaction, CommandType commandType, string commandText, params DbParameter[] commandParameters)
        {
            using (DbDataReader reader = await ExecuteReaderAsync(transaction, commandType, commandText, commandParameters))
            {
                return await ModelMapper.MapAsync<TModel>(reader);
            }
        }

        /// <summary>
        /// Execute a SqlCommand (that returns a resultset) against the specified DbTransaction
        /// using the provided parameters.
        /// </summary>
        /// <remarks>
        /// e.g.:  
        ///   DbDataReader dr = ExecuteReader(trans, CommandType.StoredProcedure, "GetOrders", new DbParameter("@productId", 24));
        /// </remarks>
        /// <param name="transaction">A valid DbTransaction</param>
        /// <param name="commandType">The CommandType (stored procedure, text, etc.)</param>
        /// <param name="commandText">The stored procedure name or T-SQL command</param>
        /// <param name="commandParameters">An array of DbParameters used to execute the command</param>
        /// <returns>A DbDataReader containing the resultset generated by the command</returns>
        public IEnumerable<TModel> ExecuteReaderToModel<TModel>(DbTransaction transaction, CommandType commandType, string commandText, IEnumerable<DbParameter> commandParameters)
        {
            using (var reader = ExecuteReader(transaction, commandType, commandText, commandParameters))
            {
                return ModelMapper.MapAsync<TModel>(reader).TaskResult();
            }
        }

        /// <summary>
        /// Execute a SqlCommand (that returns a resultset) against the specified DbTransaction
        /// using the provided parameters.
        /// </summary>
        /// <remarks>
        /// e.g.:  
        ///   Task&lt;DbDataReader&gt; result = ExecuteReaderAsync(trans, CommandType.StoredProcedure, "GetOrders", new DbParameter("@productId", 24));
        /// </remarks>
        /// <param name="transaction">A valid DbTransaction</param>
        /// <param name="commandType">The CommandType (stored procedure, text, etc.)</param>
        /// <param name="commandText">The stored procedure name or T-SQL command</param>
        /// <param name="commandParameters">An array of DbParameters used to execute the command</param>
        /// <returns>A DbDataReader containing the resultset generated by the command</returns>
        public async Task<IEnumerable<TModel>> ExecuteReaderToModelAsync<TModel>(DbTransaction transaction, CommandType commandType, string commandText, IEnumerable<DbParameter> commandParameters)
        {
            using (var reader = await ExecuteReaderAsync(transaction, commandType, commandText, commandParameters))
            {
                return await ModelMapper.MapAsync<TModel>(reader);
            }
        }

        #endregion ExecuteReaderToModel
    }
}
